name: AoC Benchmarks

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL
  RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld"

jobs:
  test:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Update Deps to pull new versions of solutions
        run: rm -rf Cargo.lock && rm -rf ~/.cargo/git && cargo update --workspace
      - name: Build AoC Benchmarks
        run: cargo build --release --workspace --all-features
      - name: Run AoC Benchmarks
        run: cargo run --release -p aoc-bench | tee log.txt
        env:
          AGE_PASSPHRASE: ${{ secrets.AGE_PASSPHRASE }}
      - name: Parse AoC Benchmarks
        run: cargo run --release -p aoc-bench-parser -- -c target/criterion -l log.txt >> $GITHUB_STEP_SUMMARY
